{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from opentrons import protocol_api, execute, simulate\n",
    "from opentrons.types import Location, Point\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import urllib.request\n",
    "import time\n",
    "import ast  # safer than eval\n",
    "#imports take roughly 1 minute"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Before running the program, please setup a server connection for a shared .csv folder. \n",
    "\n",
    "Run this in the terminal of the central computer: \n",
    "\n",
    "```\n",
    "cd: \"your protocol folder path\"\n",
    "python -m http.server 8000\n",
    "```\n",
    "\n",
    "This will open a sever to allow opentron to acess the file from: \n",
    "\n",
    "csv_path = \"http://your pc IP HERE:8000/volumes.csv\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>well</th>\n",
       "      <th>volC</th>\n",
       "      <th>volM</th>\n",
       "      <th>volY</th>\n",
       "      <th>volK</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>65</td>\n",
       "      <td>A8</td>\n",
       "      <td>71.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>71.0</td>\n",
       "      <td>58.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>66</td>\n",
       "      <td>B8</td>\n",
       "      <td>0.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>100.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>67</td>\n",
       "      <td>C8</td>\n",
       "      <td>0.0</td>\n",
       "      <td>83.6</td>\n",
       "      <td>0.0</td>\n",
       "      <td>116.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>68</td>\n",
       "      <td>D8</td>\n",
       "      <td>66.7</td>\n",
       "      <td>66.7</td>\n",
       "      <td>66.7</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>69</td>\n",
       "      <td>E8</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>70</td>\n",
       "      <td>F8</td>\n",
       "      <td>0.0</td>\n",
       "      <td>43.0</td>\n",
       "      <td>78.5</td>\n",
       "      <td>78.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>71</td>\n",
       "      <td>G8</td>\n",
       "      <td>35.7</td>\n",
       "      <td>0.0</td>\n",
       "      <td>128.6</td>\n",
       "      <td>35.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>72</td>\n",
       "      <td>H8</td>\n",
       "      <td>89.4</td>\n",
       "      <td>21.3</td>\n",
       "      <td>89.4</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   id well  volC   volM   volY   volK\n",
       "0  65   A8  71.0    0.0   71.0   58.0\n",
       "1  66   B8   0.0  100.0    0.0  100.0\n",
       "2  67   C8   0.0   83.6    0.0  116.4\n",
       "3  68   D8  66.7   66.7   66.7    0.0\n",
       "4  69   E8   NaN    NaN    NaN    NaN\n",
       "5  70   F8   0.0   43.0   78.5   78.5\n",
       "6  71   G8  35.7    0.0  128.6   35.7\n",
       "7  72   H8  89.4   21.3   89.4    0.0"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# example using the Sun Lab computer\n",
    "path = \"http://192.168.0.117:8000/BO8.csv\"\n",
    "df = pd.read_csv(path)\n",
    "# Get first and last 8 rows\n",
    "df_first = df.head(0)\n",
    "df_last = df.tail(8)\n",
    "\n",
    "# Combine them into one DataFrame (optional)\n",
    "df_combined = pd.concat([df_first, df_last], ignore_index=True)\n",
    "df_combined # Display volumes to verify"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Define functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# metadata\n",
    "metadata = {\n",
    "    \"protocolName\": \"IMOD Protocol\",\n",
    "    \"author\": \"Clara Tamura, Austin Martin\",\n",
    "    \"description\": \"Mara OT-2 Protocol for IMOD project\",\n",
    "    \"apiLevel\": \"2.19\",\n",
    "}\n",
    "\n",
    "class OpentronMara:\n",
    "    def __init__(self, protocol):\n",
    "        self.protocol = protocol\n",
    "        self.protocol._commands.clear()\n",
    "\n",
    "        # Load tipracks\n",
    "        self.tiprack_300 = protocol.load_labware('opentrons_96_tiprack_300ul', '2')\n",
    "\n",
    "        # Load Pipettes\n",
    "        self.pip300 = protocol.load_instrument('p300_single_gen2', mount='right', tip_racks=[self.tiprack_300])\n",
    "\n",
    "        # Track used tips manually\n",
    "        self.tip_log = {\n",
    "            self.pip300: {'tips': self.tiprack_300.wells(), 'next': 0},\n",
    "        }\n",
    "\n",
    "        # Set pipette buffers\n",
    "        self.pip300_buffer = 20\n",
    "\n",
    "        self.pip300.flow_rate.aspirate = 50\n",
    "        self.pip300.flow_rate.dispense = 50\n",
    "        self.pip300.flow_rate.blow_out = 100\n",
    "\n",
    "        # Load plates\n",
    "        self.plate_96 = protocol.load_labware('opentrons_96_wellplate_200ul_pcr_full_skirt', '1')\n",
    "        self.plate_96.set_offset(x=0, y=0, z=55)  # Z lowered by 1 mm\n",
    "    \n",
    "        self.plate_6 = protocol.load_labware('corning_6_wellplate_16.8ml_flat','3')\n",
    "        self.plate_6.set_offset(x=0, y=0, z=10)\n",
    "        self.source_wells = ['A1', 'A2', 'B1', 'B2']\n",
    "\n",
    "        # Home the pipettes\n",
    "        self.pip300.home()\n",
    "\n",
    "        print(\"Initialization complete.\")\n",
    "\n",
    "    def pick_up_tip(self, pipette):\n",
    "        \"\"\"Pick up the next available tip for the given pipette, with rack limit check.\"\"\"\n",
    "        next_tip_index = self.tip_log[pipette]['next']\n",
    "        tips = self.tip_log[pipette]['tips']\n",
    "        \n",
    "        if next_tip_index >= len(tips):\n",
    "            raise RuntimeError(f\"‚ùå No more tips available for {pipette.name}. Tip rack is empty!\")\n",
    "\n",
    "        tip = tips[next_tip_index]\n",
    "        pipette.pick_up_tip(tip)\n",
    "        self.tip_log[pipette]['next'] += 1\n",
    "\n",
    "    def reset_tips(self, pipette=None):\n",
    "        if pipette:\n",
    "            self.tip_log[pipette]['next'] = 0\n",
    "        else:\n",
    "            for pip in self.tip_log:\n",
    "                self.tip_log[pip]['next'] = 0\n",
    "        \n",
    "    def distribute_colors(self, df_combined: pd.DataFrame, columns):\n",
    "        self.columns = columns\n",
    "        volumes_df = df_combined[self.columns].round(1)\n",
    "        num_samples, num_solutions = volumes_df.shape\n",
    "        well_names = df_combined['well']\n",
    "        print(well_names)\n",
    "        destination = [self.plate_96.wells_by_name()[well] for well in well_names]\n",
    "\n",
    "        \n",
    "        for i in range(num_solutions):\n",
    "            self.pip300.distribute(\n",
    "                volumes_df[self.columns[i]].to_list(),\n",
    "                self.plate_6.wells(self.source_wells[i])[0],\n",
    "                destination,\n",
    "                disposal_vol=0,\n",
    "                blow_out=True,\n",
    "                blowout_location='source well',\n",
    "                new_tip='once',\n",
    "                trash=False\n",
    "            )\n",
    "        self.reset_tips(self.pip300) # Reset the tip log for the pipette after use\n",
    "        #self.print_cmd()\n",
    "        \n",
    "        \n",
    "    def print_cmd(self):\n",
    "        print(\"Printing Opentron Commands:\")\n",
    "        for cmd in self.protocol.commands():\n",
    "            print(cmd)\n",
    "    \n",
    "    def clear_protocol(self):\n",
    "        self.protocol._commands.clear()\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Initialize the OT-2\n",
    "This step will take 1.5 minutes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/data/robot_settings.json not found. Loading defaults\n",
      "Failed to initialize character device, will not be able to control gpios (lights, button, smoothiekill, smoothie reset). Only one connection can be made to the gpios at a time. If you need to control gpios, first stop the robot server with systemctl stop opentrons-robot-server. Until you restart the server with systemctl start opentrons-robot-server, you will be unable to control the robot using the Opentrons app.\n",
      "/data/deck_calibration.json not found. Loading defaults\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initialization complete.\n"
     ]
    }
   ],
   "source": [
    "protocol = execute.get_protocol_api('2.19') \n",
    "#protocol = simulate.get_protocol_api('2.19')  # Use simulate for testing\n",
    "robot = OpentronMara(protocol)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Execute pipetting command"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0    A8\n",
      "1    B8\n",
      "2    C8\n",
      "3    D8\n",
      "4    E8\n",
      "5    F8\n",
      "6    G8\n",
      "7    H8\n",
      "Name: well, dtype: object\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 403, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 414, in read_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 145, in get_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M123 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/utils.py\", line 77, in parse_rpm_response\n",
      "KeyError: 'T'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 403, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 414, in read_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 148, in get_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/utils.py\", line 85, in parse_rpm_response\n",
      "opentrons.drivers.utils.ParseError: ParseError(error_message=Unexpected argument to parse_rpm_response, parse_source=:DLE_CD)\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 403, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 414, in read_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 145, in get_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M123 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/utils.py\", line 97, in parse_labware_latch_status_response\n",
      "KeyError: 'STATUS'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 404, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 417, in read_labware_latch\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 161, in get_labware_latch_status\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/utils.py\", line 99, in parse_labware_latch_status_response\n",
      "opentrons.drivers.utils.ParseError: ParseError(error_message=Unexpected argument to parse_labware_latch_status_response, parse_source=M21SAU:DECOEDO\n",
      "21SAU:DECOE O\n",
      "M105 C:21.94 T:None)\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 403, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 414, in read_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 145, in get_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M123 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 483, in _send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/async_serial.py\", line 91, in read_until\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n",
      "  File \"/usr/lib/python3.10/site-packages/serial/serialutil.py\", line 663, in read_until\n",
      "  File \"/usr/lib/python3.10/site-packages/serial/serialposix.py\", line 595, in read\n",
      "serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 483, in _send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/async_serial.py\", line 91, in read_until\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n",
      "  File \"/usr/lib/python3.10/site-packages/serial/serialutil.py\", line 663, in read_until\n",
      "  File \"/usr/lib/python3.10/site-packages/serial/serialposix.py\", line 595, in read\n",
      "serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 403, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 414, in read_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 145, in get_rpm\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M123 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 483, in _send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/async_serial.py\", line 91, in read_until\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n",
      "  File \"/usr/lib/python3.10/site-packages/serial/serialutil.py\", line 663, in read_until\n",
      "  File \"/usr/lib/python3.10/site-packages/serial/serialposix.py\", line 595, in read\n",
      "serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n",
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n"
     ]
    }
   ],
   "source": [
    "robot.distribute_colors(df_combined, ['volC', 'volM', 'volY', 'volK'])\n",
    "\n",
    "robot.protocol._commands.clear() # Clear the command queue\n",
    "robot.tiprack_300.reset()  # Reset the tip racks to ensure a clean state"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# If user interrupts the program, reset the robot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Polling exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/poller.py\", line 98, in _poll_once\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 402, in read\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/hardware_control/modules/heater_shaker.py\", line 411, in read_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/heater_shaker/driver.py\", line 124, in get_temperature\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 435, in send_command\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 459, in send_data\n",
      "  File \"/usr/lib/python3.10/site-packages/opentrons/drivers/asyncio/communication/serial_connection.py\", line 513, in _send_data\n",
      "opentrons.drivers.asyncio.communication.errors.NoResponse: /dev/ot_module_heatershaker0: No response to 'M105 \n",
      "'\n"
     ]
    }
   ],
   "source": [
    "#robot.protocol.home()    # Home the robot\n",
    "robot.pip300.drop_tip()  # Ensure the pipette is not holding a tip before starting\n",
    "\n",
    "robot.protocol._commands.clear() # Clear the command queue\n",
    "robot.tiprack_300.reset()  # Reset the tip racks to ensure a clean state"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
